on: [push, pull_request]
name: CI
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: Bogdanp/setup-racket@v0.1
        with:
          architecture: x64
          distribution: full
          variant: regular
          version: 7.4
      - run: raco pkg install --batch --auto nemea/
      - run: raco test nemea/
    services:
      postgres:
        image: postgres:12
        ports:
          - 5432/tcp
        env:
          POSTGRES_DB: nemea
          POSTGRES_USER: nemea
          POSTGRES_PASSWORD: nemea
